sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.organization=jacobmalin
sonar.projectKey=JacobMalin_inventory-count
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.sources=lib/
sonar.tests=test/
sonar.exclusions=**/typeshed-fallback/**